# Generated by Django 3.2.6 on 2021-08-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=2000)),
                ('CreateDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('IsClosed', models.BooleanField()),
                ('RelevantUsers', models.CharField(max_length=1000)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangTixReviewer.usernames')),
            ],
            options={
                'ordering': ['Owner'],
            },
        ),
    ]
